name: Codexパッチ適用

on:
  workflow_dispatch:
    inputs:
      target_branch:
        description: 'パッチを適用するブランチ名'
        required: true
        default: 'main'
      source_branch:
        description: 'パッチファイルを取得するブランチ名（省略時はワークフローを実行したブランチ）'
        required: false
        default: ''
      patch_file:
        description: 'リポジトリルートからのパッチファイルへのパス（例: patch）'
        required: true
        default: 'patch'

jobs:
  apply-patch:
    runs-on: ubuntu-latest

    steps:
      - name: ターゲットブランチをチェックアウト
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.target_branch }}
          fetch-depth: 0

      - name: パッチファイルを取得
        env:
          PATCH_FILE: ${{ github.event.inputs.patch_file }}
          SOURCE_BRANCH_INPUT: ${{ github.event.inputs.source_branch }}
          DEFAULT_SOURCE_BRANCH: ${{ github.ref_name }}
        run: |
          SOURCE_BRANCH="$SOURCE_BRANCH_INPUT"
          if [ -z "$SOURCE_BRANCH" ]; then
            SOURCE_BRANCH="$DEFAULT_SOURCE_BRANCH"
          fi

          SOURCE_BRANCH="${SOURCE_BRANCH#refs/heads/}"
          SOURCE_BRANCH="${SOURCE_BRANCH#origin/}"

          if ! git ls-remote --exit-code origin "refs/heads/$SOURCE_BRANCH" > /dev/null; then
            echo "指定されたソースブランチ $SOURCE_BRANCH が origin に存在しません。" >&2
            exit 1
          fi

          git fetch origin "$SOURCE_BRANCH"

          PATCH_PATH="$RUNNER_TEMP/codex.patch"
          if ! git show "origin/$SOURCE_BRANCH:$PATCH_FILE" > "$PATCH_PATH"; then
            echo "ブランチ $SOURCE_BRANCH に $PATCH_FILE が存在しません。" >&2
            exit 1
          fi

          echo "パッチファイルを $SOURCE_BRANCH から取得しました。"
          echo "SOURCE_BRANCH=$SOURCE_BRANCH" >> "$GITHUB_ENV"
          echo "PATCH_PATH=$PATCH_PATH" >> "$GITHUB_ENV"

      - name: パッチのサマリーを表示
        env:
          PATCH_PATH: ${{ env.PATCH_PATH }}
        run: git apply --stat "$PATCH_PATH"

      - name: パッチを適用
        env:
          PATCH_PATH: ${{ env.PATCH_PATH }}
        run: git apply --apply --whitespace=fix "$PATCH_PATH"

      - name: 作業ツリーの状態を表示
        run: git status --short

      - name: Run tests (optional)
        if: false
        run: |
          echo "必要に応じてテストコマンドを有効化してください"

      - name: コミットを作成
        run: |
          if [ -z "$(git status --short)" ]; then
            echo "パッチ適用後の差分がありません。コミットをスキップします。"
            exit 0
          fi
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add -A
          git commit -m "Apply Codex patch"

      - name: 変更をプッシュ
        if: always()
        env:
          TARGET_BRANCH: ${{ github.event.inputs.target_branch }}
        run: |
          if git show-ref --verify --quiet refs/remotes/origin/$TARGET_BRANCH; then
            git push origin HEAD:$TARGET_BRANCH
          else
            echo "指定されたブランチ $TARGET_BRANCH が存在しません" >&2
            exit 1
          fi

      - name: Pull Request を作成
        if: ${{ github.event.inputs.target_branch != github.ref_name }}
        uses: peter-evans/create-pull-request@v6
        with:
          branch: ${{ github.event.inputs.target_branch }}
          title: "Apply Codex patch"
          body: |
            自動適用された Codex パッチを確認してください。
            - 元ブランチ: ${{ github.ref_name }}
            - パッチ取得ブランチ: ${{ env.SOURCE_BRANCH }}
            - 適用ブランチ: ${{ github.event.inputs.target_branch }}
            - パッチファイル: ${{ github.event.inputs.patch_file }}
