name: Codexパッチ適用

on:
  workflow_dispatch:
    inputs:
      target_branch:
        description: 'パッチを適用するブランチ名'
        required: true
        default: 'main'
      patch_file:
        description: 'リポジトリルートからのパッチファイルへのパス（例: patch）'
        required: true
        default: 'patch'

jobs:
  apply-patch:
    runs-on: ubuntu-latest

    steps:
      - name: ソースブランチをチェックアウト
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: パッチファイルを準備
        env:
          PATCH_FILE: ${{ github.event.inputs.patch_file }}
        run: |
          if [ ! -f "$PATCH_FILE" ]; then
            echo "ソースブランチ（${{ github.ref_name }}）に $PATCH_FILE が存在しません。" >&2
            exit 1
          fi
          PATCH_PATH="$RUNNER_TEMP/codex.patch"
          cp "$PATCH_FILE" "$PATCH_PATH"
          echo "PATCH_PATH=$PATCH_PATH" >> "$GITHUB_ENV"

      - name: ターゲットブランチをチェックアウト
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.target_branch }}
          fetch-depth: 0

      - name: パッチのサマリーを表示
        env:
          PATCH_PATH: ${{ env.PATCH_PATH }}
        run: git apply --stat "$PATCH_PATH"

      - name: パッチを適用
        env:
          PATCH_PATH: ${{ env.PATCH_PATH }}
        run: git apply --apply --whitespace=fix "$PATCH_PATH"

      - name: 作業ツリーの状態を表示
        run: git status --short

      - name: Run tests (optional)
        if: false
        run: |
          echo "必要に応じてテストコマンドを有効化してください"

      - name: コミットを作成
        run: |
          if [ -z "$(git status --short)" ]; then
            echo "パッチ適用後の差分がありません。コミットをスキップします。"
            exit 0
          fi
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add -A
          git commit -m "Apply Codex patch"

      - name: 変更をプッシュ
        if: always()
        env:
          TARGET_BRANCH: ${{ github.event.inputs.target_branch }}
        run: |
          if git show-ref --verify --quiet refs/remotes/origin/$TARGET_BRANCH; then
            git push origin HEAD:$TARGET_BRANCH
          else
            echo "指定されたブランチ $TARGET_BRANCH が存在しません" >&2
            exit 1
          fi

      - name: Pull Request を作成
        if: ${{ github.event.inputs.target_branch != github.ref_name }}
        uses: peter-evans/create-pull-request@v6
        with:
          branch: ${{ github.event.inputs.target_branch }}
          title: "Apply Codex patch"
          body: |
            自動適用された Codex パッチを確認してください。
            - 元ブランチ: ${{ github.ref_name }}
            - 適用ブランチ: ${{ github.event.inputs.target_branch }}
            - パッチファイル: ${{ github.event.inputs.patch_file }}
